[build]
builder = "RAILPACK"

[deploy]
startCommand = "gunicorn --bind [::]:$PORT app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
